In [1]:
import numpy as np
import pandas as pd

num_of_stocks = 2000  # the number of stocks given in our problem

#DataFrame is created with the csv file
df = pd.read_csv('54_hfc_20170614_comp.csv', names=range(num_of_stocks),dtype='float64')

In [2]:
#Panda's DataFrame is easier to handle, 
#but a matrix made in Numpy is much faster to call its values
corr_matrix = np.corrcoef(df.T)
corr_matrix = np.array(corr_matrix, dtype='float64')
corr_matrix.shape

(2000, 2000)

In [3]:
corr_matrix_sorted_elements_row = []
corr_matrix_sorted_200_elements_row = [] 
corr_matrix_score = []
for i in range(2000):
    corr_matrix_sorted_elements_row.append(np.flipud(corr_matrix[i].argsort()))
    corr_matrix_sorted_200_elements_row.append(corr_matrix_sorted_elements_row[i][:200])
    corr_matrix_score.append(corr_matrix[i][corr_matrix_sorted_200_elements_row[i]].sum()/corr_matrix[i][corr_matrix_sorted_elements_row[i][200:]].sum())

In [4]:
sorted_center = np.flipud(np.array(corr_matrix_score).argsort())
sorted_center[:20]

array([1837, 1862, 1579, 1650,  599, 1493, 1959,    3, 1657, 1914, 1895,
       1729, 1573, 1898, 1281, 1911, 1300, 1511, 1702, 1743])

In [5]:
corr_matrix_sorted_200_elements_row[1837]

array([1837, 1718,  142, 1849, 1775,  483, 1817,  835, 1714,  720, 1200,
       1854,  634, 1728, 1533, 1946, 1163, 1359, 1993, 1710, 1989, 1979,
       1892,  732,  509, 1797,  272, 1100, 1862,  197, 1165, 1941,  180,
       1624, 1585, 1712, 1496, 1894, 1932, 1801,  356, 1166, 1561, 1402,
       1936, 1858, 1110, 1459,  694, 1789, 1981, 1772, 1724,  599, 1897,
        121, 1192, 1864, 1896, 1003, 1511, 1771,    3, 1750,  848, 1541,
       1287, 1122, 1156, 1868,  868, 1867, 1883, 1378,  822, 1416, 1729,
       1924, 1785, 1865, 1327, 1916, 1843, 1262, 1358,  910, 1818,  756,
       1790,  865, 1524, 1784,  474, 1977, 1730, 1366, 1875,  165,  667,
       1805, 1390, 1840,  526,  995, 1764,  155, 1225, 1763,  377, 1413,
       1982,  593,  380, 1069,  668,  378,  661,  409, 1482,  275, 1300,
        902, 1918, 1803,  767,  678,  200, 1127,  653, 1436, 1241, 1734,
        662, 1391, 1802,  663,  898, 1161, 1313, 1121, 1683,  709, 1552,
       1761, 1233, 1184, 1943, 1207, 1847, 1091,  5

In [6]:
corr_matrix_sorted_200_elements_row[1862]

array([1862, 1493, 1927, 1907, 1947, 1867, 1920, 1454, 1974, 1994, 1708,
       1523, 1602, 1943, 1909, 1977, 1932, 1870,  726, 1524, 1729, 1662,
       1996, 1945, 1986, 1998,  575, 1412, 1303,  628, 1969, 1629, 1938,
       1815, 1837, 1852, 1910, 1389, 1934,  447, 1971, 1822,  641,  509,
       1577,  698,  218,  671,  703, 1889,  953,  573,  400,  894,  725,
        732,  656, 1993, 1419, 1836, 1940, 1603,  243,  737, 1842, 1259,
       1919,  175, 1675, 1983,  236, 1644, 1094,  911,  542,  507, 1922,
       1261,  832, 1499,  505, 1445,  795, 1656, 1739, 1711, 1887, 1960,
        931,   98, 1007, 1164,  653, 1782,   88, 1459, 1984, 1498, 1185,
       1979,  760,  341, 1446,  648,  364, 1284, 1202, 1615,  283, 1619,
        475,  484,  607,  982,  756, 1176,  739, 1942,  996, 1865, 1298,
       1439, 1325, 1936,  617, 1817, 1404, 1775, 1624, 1351, 1804,  881,
        478, 1767, 1339,  552,  923, 1118,  835,  922, 1126, 1881, 1710,
        887, 1301,  404,  272,  429, 1893, 1906, 14

In [36]:
len(set(corr_matrix_sorted_200_elements_row[1579])&set(corr_matrix_sorted_200_elements_row[1862]) )

18

In [13]:
def test(k, thresh):
    list_of_stocks = []
    list_of_stocks.append(corr_matrix_sorted_200_elements_row[k])

    for i in sorted_center[:200]:
        state = False
        if i != sorted_center[k]:
            #print('i=',i)
            for j in range(len(list_of_stocks)):
                #print('j=',j)
                if len(set(corr_matrix_sorted_200_elements_row[i]) & set(list_of_stocks[j]))  >= thresh:
                    #print('YES')
                    state = True
                    break
            if state != True:
                if len(list_of_stocks) < 10:
                    list_of_stocks.append(corr_matrix_sorted_200_elements_row[i])
                else:
                    break
    if len(list_of_stocks) == 10:
        return list_of_stocks

In [17]:
list_of_stocks = np.array(test(1837,100))

import matplotlib.pyplot as plt
%matplotlib inline
x = np.arange(2000)
y = np.arange(2000)
x, y = np.meshgrid(x, y)

intensity = corr_matrix.copy()[list_of_stocks.flatten(),:][:,list_of_stocks.flatten()]
plt.pcolormesh(x, y, intensity)
plt.colorbar() 
plt.show()

In [206]:
a = set()
for i in range(10):
    a.update(set(list_of_stocks[i]))
len(a) #this shows that there is no dupulicated element

1324

In [14]:
corr_matrix[0][np.flipud(corr_matrix[0].argsort())[200:]].sum()

473.32726544475793

In [39]:
sorted(corr_matrix_score, reverse=True)

[1.140471305847784,
 0.57890874883237042,
 0.57533437928560649,
 0.46108335048384458,
 0.44944423952313117,
 0.41342569109555555,
 0.41188160326205575,
 0.40118910429369076,
 0.40117443726769297,
 0.39302793288703802,
 0.39066351895804274,
 0.39041856445470891,
 0.38875500687102027,
 0.38024269362212759,
 0.37686405553608754,
 0.37646019207401854,
 0.37376193636737026,
 0.36888962088116856,
 0.36267007451884481,
 0.35972657907473421,
 0.35823125982223741,
 0.35822423888198279,
 0.35682310935012163,
 0.35440956523451272,
 0.35310460873730365,
 0.35247318035467279,
 0.34600144102277358,
 0.34572768671934179,
 0.34296601697013457,
 0.33930690418036796,
 0.33819937760885205,
 0.33591444015480854,
 0.32693462457848071,
 0.32405449185974966,
 0.31951207080573429,
 0.31547338392657848,
 0.31345487191316174,
 0.31275654153226784,
 0.31039085116607951,
 0.31002785403292382,
 0.30934321631161521,
 0.30885387304815459,
 0.30525921167527692,
 0.30518112630538335,
 0.30429512039028705,
 0.300116336

In [76]:
eigenvalues, eigenvectors = np.linalg.eig(corr_matrix)

In [79]:
eigenvalues[eigenvalues<0]

array([], dtype=float64)

In [11]:
#defining the functions for calculating TICS, CARS and the value to be minimized

def Calc_IC(sub_group_of_stocks):
    return np.corrcoef(df.loc[:,sub_group_of_stocks].T).sum()

def Calc_TICS(list_of_stocks):
    TICS = {}
    for i in range(len(list_of_stocks)):
        TICS[i]=(Calc_IC(list_of_stocks[i])) #here the number i is the group number
    return sum(TICS.values())

def Calc_CARS(list_of_stocks): 
    CARS_dict = {}
    CARS_dict.update({'AR{}'.format(i): df[list_of_stocks[i]].mean(axis=1) for i in range(10)})

    temp_list = []
    for i in range(10):
        temp_list.append(CARS_dict['AR{}'.format(i)])
    
    CARS = np.corrcoef(temp_list).sum()
    return CARS

def objective_function(list_of_stocks):
    return Calc_CARS(list_of_stocks)/Calc_TICS(list_of_stocks)



In [81]:
def find_stock_group(list_of_stocks, stock_number):
    for i in range(10):
        if stock_number in list_of_stocks[i]:
            return (stock_number, i)  #i is the group number 
        
def find_stock_location(list_of_stocks, stock_number):
    for i in range(10):
        if stock_number in list_of_stocks[i]:
            for j in range(200):
                if stock_number == list_of_stocks[i,j]:
                    return (i,j)  #i is the group number and j is the location within the group


In [82]:
#this part below is the list of functions used when the each group is formed

#find_the_next_min function is used to find the next element within a group when the group is formed
def find_the_next_min(group, reference_set):
    index, min_ = 0, 9999  #initialization of the variables
    for i in reference_set:
        if i not in group:
            intra_value = sum([corr_matrix[element,i] for element in group])
            inter_value = (corr_matrix[i].sum() - 2*intra_value - 1)
            value = abs(inter_value/intra_value)
            if value < min_:
                index, min_ = i, value
    return (index, min_)

#using the find_the_next_min function, group elements are added until its number reaches 200
def add_element_to_group(group, reference_set):
    while len(group) < 200:
        group.append(find_the_next_min(group, reference_set)[0])

#when one group is formed, the first element in the next group is found using find_the_next_max function
def find_the_next_max(reference_set):
    group_list = list(set(range(2000)) - reference_set)
    index, max_ = 0, -9999
    for i in reference_set:
        intra_value = sum([corr_matrix[element,i] for element in group_list])
        inter_value = (corr_matrix[i].sum() - 2*intra_value - 1)
        value = abs(inter_value/intra_value)
        if value > max_:
            index, max_ = i, value
    return (index, max_)

In [68]:
def find_partitions(reference_set):
    for i in range(10):
        add_element_to_group(eval('group_{}'.format(i)), reference_set)
        reference_set = reference_set - set(eval('group_{}'.format(i)))
        #print('group_{} has been made'.format(i))
        i += 1
        if i != 10:
            eval('group_{}'.format(i)).append(find_the_next_max(reference_set)[0])

    
initial_param_result = []

    
def find_the_initial_parameter(num_of_repetition):
    
    initial_min = 0.000562
    current_min = initial_min
    
    
    for k in range(num_of_repetition):
        
        print(k, '-repetition has started')
        #temp list of stocks before partitioning
        list_of_stocks = np.arange(2000).reshape(10,200)
        reference_set = set(list(range(1,2000)))
        initial_stock_picked = np.random.choice(list(reference_set))

        for i in range(10):  
            temp = ''           
            temp = 'group_'+str(i)+'=[]'
            exec(temp)

        group_0.append(initial_stock_picked)    

        for i in range(10):
            add_element_to_group(eval('group_{}'.format(i)), reference_set)
            reference_set = reference_set - set(eval('group_{}'.format(i)))
            i += 1
            if i != 10:
                eval('group_{}'.format(i)).append(find_the_next_max(reference_set)[0])    

        for i in range(10):
            list_of_stocks[i] = eval('group_{}'.format(i))

        result = objective_function(list_of_stocks)
        if  result < current_min:
            current_min = result
            print((initial_stock_picked, result))
            initial_param_result.append((initial_stock_picked, result))
            

  

In [69]:
find_the_initial_parameter(100)

0 -repetition has started


/Users/Sungwookhong/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:10: RuntimeWarning: divide by zero encountered in double_scalars


1 -repetition has started
2 -repetition has started
3 -repetition has started
4 -repetition has started
5 -repetition has started
6 -repetition has started
7 -repetition has started
8 -repetition has started
9 -repetition has started
10 -repetition has started
11 -repetition has started
12 -repetition has started
13 -repetition has started
14 -repetition has started
15 -repetition has started
16 -repetition has started
17 -repetition has started
18 -repetition has started
19 -repetition has started
20 -repetition has started
21 -repetition has started
22 -repetition has started
23 -repetition has started
24 -repetition has started
25 -repetition has started
26 -repetition has started
27 -repetition has started
28 -repetition has started
29 -repetition has started
30 -repetition has started
31 -repetition has started
32 -repetition has started
33 -repetition has started
34 -repetition has started
35 -repetition has started
36 -repetition has started
37 -repetition has started
38 -repeti

In [ ]:
temp_list = np.arange(2000)

In [23]:
#now I need the functions for optimization after the whole 10 groups are formed
def intra_group_sum_corr_matrix(stock_list, group_number):
    return np.sum(corr_matrix[stock_list[group_number], :][:, stock_list[group_number]])

def inter_group_sum_corr_matrix(stock_list, group_number):
    return np.sum(corr_matrix[stock_list[group_number], :])-intra_group_sum_corr_matrix(stock_list, group_number)

initial_sum_intra = []
initial_sum_inter = []

def initialize_sum(list_of_stocks):
    stock_list = list_of_stocks.copy()
    for i in range(10):
        initial_sum_intra.append(intra_group_sum_corr_matrix(stock_list, i))
        initial_sum_inter.append(inter_group_sum_corr_matrix(stock_list, i))

initialize_sum(list_of_stocks)
initial_score = np.array(initial_sum_inter)/np.array(initial_sum_intra)
#we want the small inter_sum and large intra_sum, meaning that the smaller value of the equation 
#above is preferred

initial_score


array([ 7.54282309,  5.61856194,  5.69548588,  9.37406704,  6.39297563,
        7.02680248,  9.25433509,  7.15698174,  6.49348565,  7.67428755])

In [56]:
current_score

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [34]:
current_score = initial_score.copy()

stock_location_dict = {}
for i in range(num_of_stocks):
    stock_location_dict[i] = find_stock_location(list_of_stocks, i)
    #for exmaple, stock_location_dict[0] = (1,3) means the location is group_1 and 3 within group_1 
    
#in this method, stock_location_dict needs to be updated whenever locations changed
def fast_stock_location(stock_number):
    return stock_location_dict[stock_number]

#swap function will be used when exchanging a pair of stocks between two different groups
#it exchanges the location of stock1 with that of stock2 in list_of_stocks
def swap(list_of_stocks,stock1,stock2):
    stock_list = list_of_stocks.copy()
    loc_of_stock1 = fast_stock_location(stock1)
    loc_of_stock2 = fast_stock_location(stock2)
    stock_list[loc_of_stock1], stock_list[loc_of_stock2] = stock_list[loc_of_stock2], stock_list[loc_of_stock1]
    return stock_list
    
    #list_of_stocks = swap(list_of_stocks, stock1, stock2)
    #stock_location_dict.update({stock1:loc_of_stock2, stock2: loc_of_stock1})

def swap_between_groups(list_of_stocks, group1, group2):
    min_ = 9999  #initialization of the variables
    
    current_score_for_two = current_score[group1]+current_score[group2] 
    
    for stock1 in list_of_stocks[group1]:
        for stock2 in list_of_stocks[group2]:
        
            stock_list = swap(list_of_stocks,stock1,stock2)
        
            intra_value_1 = intra_group_sum_corr_matrix(stock_list, group1)
            inter_value_1 = intra_group_sum_corr_matrix(stock_list, group1)
            score_1 = inter_value_1/intra_value_1

            intra_value_2 = intra_group_sum_corr_matrix(stock_list, group2)
            inter_value_2 = intra_group_sum_corr_matrix(stock_list, group2)
            score_2 = inter_value_2/intra_value_2

            if score_1 + score_2 < current_score_for_two:
                list_of_stocks = stock_list.copy()
                loc_of_stock1 = fast_stock_location(stock1)
                loc_of_stock2 = fast_stock_location(stock2)
                stock_location_dict.update({stock1:loc_of_stock2, stock2: loc_of_stock1})
                current_score[group1] = score_1
                current_score[group2] = score_2
                
def optimize_corr_matrix(list_of_stocks):
    for i in range(10):
        for j in range(10):
            if i == j:
                continue
            print('optimizing group_{} with group_{}'.format(i, j),'has started its loop')
            swap_between_groups(list_of_stocks, i, j)

In [38]:
optimize_corr_matrix(list_of_stocks)

optimizing group_0 with group_1 has started its loop
optimizing group_0 with group_2 has started its loop
optimizing group_0 with group_3 has started its loop
optimizing group_0 with group_4 has started its loop
optimizing group_0 with group_5 has started its loop
optimizing group_0 with group_6 has started its loop
optimizing group_0 with group_7 has started its loop
optimizing group_0 with group_8 has started its loop
optimizing group_0 with group_9 has started its loop
optimizing group_1 with group_0 has started its loop
optimizing group_1 with group_2 has started its loop
optimizing group_1 with group_3 has started its loop
optimizing group_1 with group_4 has started its loop
optimizing group_1 with group_5 has started its loop
optimizing group_1 with group_6 has started its loop
optimizing group_1 with group_7 has started its loop
optimizing group_1 with group_8 has started its loop
optimizing group_1 with group_9 has started its loop
optimizing group_2 with group_0 has started it

In [39]:
objective_function(list_of_stocks)

0.0005616102499263545

In [10]:
initial_list_of_stocks = list_of_stocks.copy()
current_min = objective_function(initial_list_of_stocks)

In [11]:
objective_function(initial_list_of_stocks)
#list_of_stocks = initial_list_of_stocks.copy()

0.00056183968503703162

In [40]:
list_of_stocks

array([[1890, 1729, 1862, ..., 1926, 1196, 1361],
       [ 735, 1579,  827, ...,  893,   64, 1757],
       [   3, 1895, 1911, ...,   59, 1705, 1864],
       ..., 
       [1052, 1189, 1226, ...,  716,   45,  139],
       [1592, 1825, 1732, ...,  540, 1339, 1238],
       [1415, 1166,  971, ...,  500,   48,    0]])

In [51]:
list(stock_location_dict[0])
alternative_list

0

In [52]:
alternative_list = np.arange(2000).reshape((10,200))
for i in range(2000):
    alternative_list[list(stock_location_dict[i])[0],list(stock_location_dict[i])[1]] = i
    
alternative_list

array([[ 467,   40,  452, ..., 1678, 1601, 1568],
       [1430,  468,  610, ..., 1815,  765, 1810],
       [1322,  855, 1117, ..., 1312,  345,  231],
       ..., 
       [1891, 1443,  980, ..., 1321,  742,  409],
       [1126,  782, 1317, ..., 1221, 1330, 1358],
       [1509, 1138, 1927, ...,  319, 1862, 1890]])

In [53]:
objective_function(alternative_list)

0.00087510850628080231

In [12]:
stock_location_dict = {}
for i in range(num_of_stocks):
    stock_location_dict[i] = find_stock_location(list_of_stocks, i)

#in this method, stock_location_dict needs to be updated whenever locations changed
def fast_stock_location(stock_number):
    return stock_location_dict[stock_number]

#swap function will be used when exchanging a pair of stocks between two different groups
def swap_without_return(list_of_stocks,stock1,stock2):
    loc_of_stock1 = fast_stock_location(stock1)
    loc_of_stock2 = fast_stock_location(stock2)
    list_of_stocks[loc_of_stock1], list_of_stocks[loc_of_stock2] = list_of_stocks[loc_of_stock2], list_of_stocks[loc_of_stock1]
    stock_location_dict.update({stock1:loc_of_stock2, stock2: loc_of_stock1})

In [13]:
reference_total = set(np.arange(2000))
def find_the_min(list_of_stocks, group_list, stock_loc): #stock_loc is the location index within the group
    stock = group_list[stock_loc]
    reference = reference_total - set(group_list) | {stock}
    result = find_the_next_min(np.delete(group_list,stock_loc), reference)
    global current_min
    if result[0] != stock: 
        swap(list_of_stocks, stock, result[0])
        temp_ = objective_function(list_of_stocks)
        if  temp_ < current_min:
            current_min = temp_
            print('Swapped, now the min value is', current_min)
        else: 
            swap(list_of_stocks, stock, result[0])
            

In [14]:
current_min

0.00056183968503703162

In [15]:
def optimize_the_first_part(list_of_stocks):
    for i in range(50): #here i is the column number (first i elements in each group)
        print(i, 'has started')
        for j in range(10): #j is the row number (group number)
            find_the_min(list_of_stocks, list_of_stocks[j],i)

def random_optimize(list_of_stocks, num_of_iteration):
    for i in range(num_of_iteration):
        find_the_min(list_of_stocks, list_of_stocks[np.random.randint(10)],np.random.randint(200))

def optimize_the_second_part(list_of_stocks):
    for i in range(150,200): #here i is the column number (first i elements in each group)
        print(i, 'has started')
        for j in range(10): #j is the row number (group number)
            find_the_min(list_of_stocks, list_of_stocks[j],i)
            
def optimize_the_whole_part(list_of_stocks, num_of_iteration):
    for number in range(num_of_iteration):
        optimize_the_first_part(list_of_stocks)
        optimize_the_second_part(list_of_stocks)

In [16]:
optimize_the_whole_part(list_of_stocks,1)

0 has started
Swapped, now the min value is 0.000561406585407
1 has started
Swapped, now the min value is 0.00056136874099
2 has started
3 has started
Swapped, now the min value is 0.00056129784413
4 has started
5 has started
Swapped, now the min value is 0.000561283836741
6 has started
7 has started
8 has started
9 has started
10 has started
11 has started
Swapped, now the min value is 0.000561264831862
12 has started
13 has started
14 has started
15 has started
16 has started
17 has started
18 has started
19 has started
20 has started
Swapped, now the min value is 0.000561249947149
21 has started
22 has started
23 has started
Swapped, now the min value is 0.000561205596527
24 has started
25 has started
26 has started
27 has started
28 has started
29 has started
Swapped, now the min value is 0.000561108989494
30 has started
31 has started
32 has started
33 has started
34 has started
35 has started
36 has started
37 has started
38 has started
Swapped, now the min value is 0.00056105308

In [17]:
answer_list = list_of_stocks.copy()

In [18]:
current_min

0.00056049483503055894

In [55]:
a = set()
for i in range(10):
    a.update(set(list_of_stocks[i]))
len(a) #this shows that there is no dupulicated element

2000

In [37]:
objective_function(answer_list)

NameError: name 'answer_list' is not defined

In [48]:
def minimize(list_of_stocks, fixed_row = 0,fixed_col = 199):
    result = {}
    global current_min
    
    for i in range(0,10):
        if i != fixed_row: #here being in the same row means being in the same group - so avoids the case
            print(i, 'started')
            for j in range(0,199):
                temp_list = list_of_stocks.copy()
                swap(temp_list,temp_list[fixed_row,j],temp_list[i,fixed_col])
                temp_ = objective_function(temp_list)
                if  temp_ < current_min:
                    current_min = temp_
                    print('found',(list_of_stocks[fixed_row,j],list_of_stocks[i,fixed_col]), temp_)
                    result[(list_of_stocks[fixed_row,j],list_of_stocks[i,fixed_col])] = temp_ 
    return result
swap(list_of_stocks, stock, result[0])
        temp_ = objective_function(list_of_stocks)
        if  temp_ < current_min:
            current_min = temp_
            print('Swapped, now the min value is', current_min)
        else: 
            swap(list_of_stocks, stock, result[0])
#starting fixed_row = 0, fixed_col = 199
#in the swapping process, 
#I chose the very last elements in each group first as they contribute to the TICS the least

In [84]:
objective_function(list_of_stocks)

0.0005616102499263545

In [115]:
%time
import matplotlib.pyplot as plt
%matplotlib inline
x = np.arange(2000)
y = np.arange(2000)
x, y = np.meshgrid(x, y)

#convert intensity (list of lists) to a numpy array for plotting
intensity = corr_matrix.copy()[list_of_stocks.flatten(),:][:,list_of_stocks.flatten()]

#now just plug the data into pcolormesh, it's that easy!
plt.pcolormesh(x, y, intensity)
plt.colorbar() #need a colorbar to show the intensity scale
plt.show()

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 4.05 µs


In [107]:
np.array(list(list_of_stocks.flatten()))

(2000,)